[package]
name = "majordome-derive"
version = "1.0.6"
edition = "2021"
description = "Derive macros for the majordome crate"
license = "MIT"
repository = "https://github.com/merlleu/majordome"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
cfg-if = "1.0"
proc-macro2 = "1.0.86"
